### PR TITLE
More turn ending opportunities and minor UI fixes

### LINKED ISSUE #114: Clicking end turn does not always end the turn
Depending on the current state of the game, clicking the end turn button will sometimes not do anything because there is no event for it in the current state. Clicking the end turn button should always end the turn regardless of the current state

### LINKED ISSUE #172: to many cards => can't "End turn"

### LINKED ISSUE #183: Policy screen click throught
ability tokens and other game elements are clickable thought Policies screen
image

### PR DESCRIPTION
**Pull request by DreyerChris**
- Fixes #183 
- Fixes #172 
- Fixes #114 
- Minor UI fixes

### CODE REVIEW

File: src/state/machines/turn.ts [hunk 1]
```diff
@@ -725,6 +725,9 @@ export const TurnMachine = setup({
     },
     checkingEventConditions: {
       initial: "main",
+      on: {
```
Comment (DreyerChris) [inline src/state/machines/turn.ts:728]: I tried moving this event to the top level "turn" state, but this allows this button to be pressed always, meaning you can keep on pressing it until you have a card draw you are happy with before actually ending the turn. The simplest solution I came up with now is that ending turn is essentially allowed in two states:

- Buying
- Using ability

The reason why it has also been added to event conditions is to prevent the button from flashing when putting cards in play (because this transitions to checking event conditions before #turn.buying)

Comment (H1D) [reply src/state/machines/turn.ts:728]: OK. So we now explicitly stating in which states endTurn is possible. This approach definitely has it's benefits.

**Review by H1D — APPROVED** [review]

File: src/state/machines/turn.ts (hunk 1 above)
Comment (DreyerChris) [reply src/state/machines/turn.ts:728]: Yes exactly, yeah I think this is better than writing a bunch of guards and logic of when the turn should actually be able to be ended
