### PR TITLE
demo5 fixes

### LINKED ISSUE #85: Seed to URL
Propagate seed to URL when game has started

### LINKED ISSUE #141: No borrow limit
As is turned out resource borrowing is unlimited.

### PR DESCRIPTION
**Pull request by H1D**
- **persist seed to URL; closes #85**
- **no limit for borrow; closes #141**
- **updated assets**

### CODE REVIEW

File: src/state/machines/turn.ts [hunk 1]
```diff
@@ -1039,6 +1042,14 @@ export const TurnMachine = setup({
               },
             },
             pickingDestination: {
+              always: {
```
Comment (DreyerChris) [inline src/state/machines/turn.ts:1045]: I believe this implementation is wrong. In the single player rule the player has the `choice` to select their own deck as a destination, but they should still be able to select one of the market decks instead if they would like the plant/animal card to move there

Comment (DreyerChris) [reply src/state/machines/turn.ts:1045]: image

Comment (H1D) [reply src/state/machines/turn.ts]: fixed

**Review by DreyerChris — APPROVED** [review]
